# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
image:
  registry: "ghcr.io"
  repository: "talweg/kbot"
  tag: "v1.0.3-2dc87fa"
  os: linux
  arch: amd64
secret:
  name: "kbot"
  tokenKey: "token"
  tokenName: "TELE_TOKEN"
